image: haskell:8.10.7

variables:
  STACK_ROOT: "${CI_PROJECT_DIR}/.stack-root"

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .stack-work/
    - .stack-root/

build:elves:
  stage: build
  script:
    - stack build

test:elves:
  stage: test
  needs: ["build:elves"]
  script:
    - stack test

test:puzzles:
  stage: test
  needs: ["test:elves"]
  script:
    - echo $YEAR
    - bin/run-year
  parallel:
    matrix:
      - YEAR: [2017, 2018, 2021]
