image: haskell:8.10.7

variables:
  STACK_ROOT: "${CI_PROJECT_DIR}/.stack-root"

cache:
  key:
    files:
      - package.yaml
      - stack.yaml
      - stack.yaml.lock
      - Makefile
  paths:
    - .stack-work/
    - .stack-root/
    - dist/
    - dist-newstyle/
    - build/

before_script:
  - stack config set system-ghc --global true

build:elves:
  stage: build
  script:
    - stack build

build:puzzles:
  stage: build
  needs: ["build:elves"]
  script:
    - ./bin/build-year
  parallel:
    matrix:
      - YEAR:
          - 2021
          - 2019
          - 2018
          - 2017

test:elves:
  stage: test
  needs: ["build:elves"]
  script:
    - stack test

.puzzles:
  stage: test
  needs: ["test:elves", "build:puzzles"]
  script:
    - stack run $YEAR $DAY test
    - stack run $YEAR $DAY pt1
    - stack run $YEAR $DAY pt2

test:puzzles:2021:
  extends: .puzzles
  parallel:
    matrix:
      - YEAR: 2021
        DAY:
          - 1
          - 2
          - 3
          - 4
          - 5
          - 6
          - 7
          - 8
          - 9
          - 10
          - 11
          - 12
          - 13
          - 14
          - 15
          - 16
          - 17
          - 18

test:puzzles:2017:
  extends: .puzzles
  parallel:
    matrix:
      - YEAR: 2021
        DAY:
          - 1
          - 2
          - 3
          - 4
          - 5
          - 6
          - 7
          - 8
          - 9
          - 10
          - 11
          - 12
          - 13
          - 14
          - 15
          - 16
          - 17
          - 18
          - 19
          - 20
          - 21
          - 22
          - 23
          - 24
          - 25
