image: haskell:8.10.7

variables:
  STACK_ROOT: "${CI_PROJECT_DIR}/.stack-root"

stages:
  - build
  - test
  - lint

cache:
  key:
    files:
      - package.yaml
      - stack.yaml
  paths:
    - .stack-work/
    - .stack-root/
    - dist/
    - dist-newstyle/
    - build/

before_script:
  - stack config set system-ghc --global true

build:elves:
  stage: build
  script:
    - stack build

lint:
  stage: lint
  image: coorde/hlint
  script:
    - hlint src
    - hlint test
    - hlint app

test:elves:
  stage: test
  needs: ["build:elves"]
  script:
    - stack test

test:puzzles:
  stage: test
  needs: ["test:elves"]
  script:
    - ./bin/run-year
  parallel:
    matrix:
      - YEAR:
          - 2017
          - 2019
          - 2018
          - 2021
