name:                adventofcode
version:             0.1.0.0
github:              "alexkalderimis/adventofcode"
license:             BSD3
author:              "Alex Kalderimis"
maintainer:          "alex.kalderimis@gmail.com"
copyright:           "MIT"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/alexkalderimis/adventofcode#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
    - psqueues
    - array
    - containers
    - time
    - mtl
    - parsers
    - hspec
    - vector
    - vector-instances
    - unordered-containers
    - hashable
    - text
    - QuickCheck
    - async
    - comonad
    - attoparsec
    - bytestring
    - lens

executables:
  adventofcode-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - adventofcode
    - psqueues
    - array
    - containers
    - time
    - mtl
    - parsers
    - hspec
    - vector
    - vector-instances
    - unordered-containers
    - hashable
    - text
    - QuickCheck
    - async
    - comonad
    - attoparsec
    - bytestring
    - lens

tests:
  adventofcode-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - adventofcode
